import { XrayConfig } from '../types';

export class XrayExporter {
  // Export as Plain Text URIs
  static toPlainText(configs: XrayConfig[]): string {
    return configs.map(c => c.raw).join('\n');
  }

  // Export as Base64 Subscription Link content
  static toBase64(configs: XrayConfig[]): string {
    const plain = this.toPlainText(configs);
    try {
      return btoa(unescape(encodeURIComponent(plain)));
    } catch {
      return btoa(plain);
    }
  }

  // Export as Clash Meta / Mihomo YAML configuration
  static toClashMetaYaml(configs: XrayConfig[]): string {
    const proxiesYaml: string[] = [];
    const proxyNames: string[] = [];

    configs.forEach((c, idx) => {
      const name = (c.remarks || `Proxy-${idx + 1}`).replace(/[:#\[\]]/g, '').trim() || `Proxy-${idx + 1}`;
      proxyNames.push(name);

      if (c.protocol === 'vless') {
        proxiesYaml.push(`  - name: "${name}"
    type: vless
    server: ${c.address}
    port: ${c.port}
    uuid: ${c.uuid || ''}
    udp: true
    tls: ${c.security === 'tls' || c.security === 'reality'}
    servername: ${c.sni || c.host || c.address}
    client-fingerprint: ${c.fingerprint || 'chrome'}
    flow: ${c.flow || ''}
    ${c.security === 'reality' ? `reality-opts:
      public-key: ${c.pbk || ''}
      short-id: ${c.sid || ''}` : ''}
    ${c.path ? `network: ws
    ws-opts:
      path: "${c.path}"
      headers:
        Host: "${c.host || c.sni || c.address}"` : ''}`);
      } else if (c.protocol === 'vmess') {
        proxiesYaml.push(`  - name: "${name}"
    type: vmess
    server: ${c.address}
    port: ${c.port}
    uuid: ${c.uuid || ''}
    alterId: 0
    cipher: ${c.cipher || 'auto'}
    udp: true
    tls: ${c.security === 'tls'}
    servername: ${c.sni || c.host || c.address}
    ${c.path ? `network: ws
    ws-opts:
      path: "${c.path}"
      headers:
        Host: "${c.host || c.sni || c.address}"` : ''}`);
      } else if (c.protocol === 'trojan') {
        proxiesYaml.push(`  - name: "${name}"
    type: trojan
    server: ${c.address}
    port: ${c.port}
    password: ${c.password || ''}
    udp: true
    sni: ${c.sni || c.address}
    client-fingerprint: ${c.fingerprint || 'chrome'}
    ${c.path ? `network: ws
    ws-opts:
      path: "${c.path}"` : ''}`);
      } else if (c.protocol === 'ss') {
        proxiesYaml.push(`  - name: "${name}"
    type: ss
    server: ${c.address}
    port: ${c.port}
    cipher: ${c.cipher || 'aes-256-gcm'}
    password: "${c.password || ''}"
    udp: true`);
      } else if (c.protocol === 'hysteria2') {
        proxiesYaml.push(`  - name: "${name}"
    type: hysteria2
    server: ${c.address}
    port: ${c.port}
    password: "${c.hyAuth || ''}"
    sni: ${c.sni || c.address}
    skip-cert-verify: true
    ${c.hyUp ? `up: ${c.hyUp}` : ''}
    ${c.hyDown ? `down: ${c.hyDown}` : ''}
    ${c.hyObfs ? `obfs: ${c.hyObfs}
    obfs-password: "${c.hyObfsPassword || ''}"` : ''}`);
      } else if (c.protocol === 'wireguard') {
        proxiesYaml.push(`  - name: "${name}"
    type: wireguard
    server: ${c.address}
    port: ${c.port}
    ip: ${c.wgLocalIp || '10.0.0.2'}
    public-key: ${c.wgPublicKey || ''}
    private-key: ${c.wgPrivateKey || ''}
    udp: true
    remote-dns-resolve: true`);
      }
    });

    const yamlHeader = `# Clash Meta / Mihomo Configuration
# Generated by XrayMultiTest
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info
ipv6: false

proxies:
${proxiesYaml.join('\n\n')}

proxy-groups:
  - name: "PROXIES_AUTO"
    type: url-test
    url: "https://cp.cloudflare.com/generate_204"
    interval: 300
    proxies:
${proxyNames.map(n => `      - "${n}"`).join('\n')}

  - name: "MANUAL_SELECT"
    type: select
    proxies:
      - "PROXIES_AUTO"
${proxyNames.map(n => `      - "${n}"`).join('\n')}

rules:
  - MATCH,MANUAL_SELECT
`;
    return yamlHeader;
  }

  // Export as Sing-box Outbounds JSON
  static toSingboxJson(configs: XrayConfig[]): string {
    const outbounds: any[] = [];

    configs.forEach((c, idx) => {
      const tag = (c.remarks || `node-${idx + 1}`).trim();

      if (c.protocol === 'vless') {
        const outbound: any = {
          type: "vless",
          tag,
          server: c.address,
          server_port: c.port,
          uuid: c.uuid || "",
          flow: c.flow || undefined
        };

        if (c.security === 'tls' || c.security === 'reality') {
          outbound.tls = {
            enabled: true,
            server_name: c.sni || c.host || c.address,
            utls: {
              enabled: true,
              fingerprint: c.fingerprint || 'chrome'
            }
          };

          if (c.security === 'reality') {
            outbound.tls.reality = {
              enabled: true,
              public_key: c.pbk || "",
              short_id: c.sid || ""
            };
          }
        }

        if (c.path) {
          outbound.transport = {
            type: "ws",
            path: c.path,
            headers: {
              Host: c.host || c.sni || c.address
            }
          };
        }

        outbounds.push(outbound);
      } else if (c.protocol === 'trojan') {
        outbounds.push({
          type: "trojan",
          tag,
          server: c.address,
          server_port: c.port,
          password: c.password || "",
          tls: {
            enabled: true,
            server_name: c.sni || c.address,
            utls: {
              enabled: true,
              fingerprint: c.fingerprint || 'chrome'
            }
          }
        });
      } else if (c.protocol === 'ss') {
        outbounds.push({
          type: "shadowsocks",
          tag,
          server: c.address,
          server_port: c.port,
          method: c.cipher || "aes-256-gcm",
          password: c.password || ""
        });
      } else if (c.protocol === 'hysteria2') {
        outbounds.push({
          type: "hysteria2",
          tag,
          server: c.address,
          server_port: c.port,
          password: c.hyAuth || "",
          tls: {
            enabled: true,
            server_name: c.sni || c.address
          }
        });
      }
    });

    const fullConfig = {
      version: 1,
      log: { level: "info", timestamp: true },
      outbounds: [
        {
          type: "selector",
          tag: "proxy-select",
          outbounds: outbounds.map(o => o.tag)
        },
        ...outbounds,
        { type: "direct", tag: "direct" },
        { type: "block", tag: "block" }
      ]
    };

    return JSON.stringify(fullConfig, null, 2);
  }
}
