import { Translation } from './types';

export const PersianTranslation: Translation = {
  appName: "ایکس ری مالتی تست",
  currentCoreVersion: "نسخه فعلی هسته: ",
  latestCoreVersion: "آخرین نسخه منتشر شده: ",
  checkVersionBtn: "بررسی نسخه جدید هسته",
  downloadCoreBtn: "دانلود و بروزرسانی هسته",
  selectConfigTitle: "وارد کردن کانفیگ‌ها",
  importClipboard: "وارد کردن از کلیپ‌بورد",
  importFile: "وارد کردن از فایل متنی",
  importSubLink: "دریافت از لینک اشتراک",
  subUrlPlaceholder: "آدرس لینک اشتراک را وارد کنید",
  runTestsBtn: "شروع عیب‌یابی و تست",
  testResultsTitle: "نتایج ارزیابی کانفیگ‌ها",
  tcpPingLabel: "تأخیر TCP",
  jitterLabel: "جیتر (نوسان)",
  packetLossLabel: "پکت لاست",
  realDelayLabel: "تأخیر واقعی (HTTP)",
  downloadSpeedLabel: "سرعت دانلود",
  uploadSpeedLabel: "سرعت آپلود",
  websiteCheckLabel: "بررسی سایت‌های منتخب",
  statusChecking: "در حال ارزیابی...",
  statusSuccess: "متصل و سالم",
  statusFailed: "عدم اتصال",
  exportHealthyBtn: "خروجی و کپی سالم‌ها",
  copySuccessMsg: "کانفیگ‌ها با موفقیت در کلیپ‌بورد کپی شدند!",
  settingsTitle: "شخصی‌سازی تنظیمات تست",
  localSocksPort: "پورت محلی SOCKS",
  testTimeout: "زمان انتظار تست (ms)",
  customDomains: "سایت‌های تست دسترسی",
  languageBtn: "تغییر زبان (EN)",
  unknown: "نامشخص",
  progressDownloading: "در حال دریافت باینری هسته...",
  progressExtracting: "در حال نصب و استخراج هسته...",
  fragmentSettings: "پیکربندی فرگمنت (مبارزه با فیلترینگ SNI)",
  enableFragment: "فعالسازی فرگمنت ترافیکی",
  fragmentLength: "طول بازه بایت‌های فرگمنت",
  fragmentInterval: "میزان تأخیر بین فرگمنت‌ها (ms)",
  muxSettings: "پیکربندی چندگانه‌سازی (Mux / XUDP)",
  enableMux: "فعالسازی مالتی‌پلکسر ترافیک",
  muxConcurrency: "حداکثر کانکشن‌های همزمان TCP",
  xudpConcurrencyLabel: "همزمانی تونل‌های XUDP",
  tlsFingerprint: "شبیه‌ساز اثر انگشت uTLS",

  // Personas
  personaTitle: "پرسونا و هدف تست شبکه",
  personaGaming: "گیمینگ و آنلاین",
  personaGamingDesc: "سنجش پینگ بسیار پایین، کمترین جیتر و صفر درصد پکت‌لاست",
  personaStreaming: "استریم و دانلود",
  personaStreamingDesc: "حداکثر پهنای باند دانلود، تست ترافیکی یوتیوب و پایداری ویدیو",
  personaAi: "هوش مصنوعی و وبگردی",
  personaAiDesc: "اطمینان از دسترسی کامل به جمنای، ChatGPT، اینستاگرام و تلگرام",
  personaUpload: "آپلود و تبادل دیتا",
  personaUploadDesc: "حداکثر نرخ بارگذاری، پایداری اتصالات طولانی ابری",
  personaAllRounder: "بنچمارک جامع",
  personaAllRounderDesc: "سنجش همه‌جانبه تمام فاکتورها جهت رتبه‌بندی دقیق بهترین کانفیگ‌ها",

  // Presets & Filters
  testProfileLabel: "پروفایل تنظیمات تست",
  profileUltra: "برق‌آسا (سریع و سبک)",
  profileBalanced: "متعادل (پیش‌فرض)",
  profileStable: "دقیق و پایدار (بار سنگین)",
  profileCustom: "سفارشی (کاستوم)",
  pingCountLabel: "تعداد پینگ‌های جیتر",
  speedVolumeLabel: "حجم دانلود تستی (MB)",
  speedProtocolLabel: "پروتکل تست سرعت",
  fragmentProfileLabel: "پروفایل فرگمنت ترافیکی",
  fragmentMci: "همراه اول (بای‌پَس استاندارد)",
  fragmentMtn: "ایرانسل شدید (بایت‌های بسیار ریز)",
  fragmentTcp: "تقسیم‌بندی TCP (فوق‌پایدار)",
  fragmentCustom: "سفارشی (کاستوم)",
  copyAllConfigs: "کپی تمام کانفیگ‌های سالم",
  copyLimitedConfigs: "کپی تعداد مشخص (کانفیگ‌های برتر)",
  copyLimitCountLabel: "تعداد کانفیگ‌های برتر جهت دریافت",
  addWebsiteBtn: "افزودن وب‌سایت جدید",
  editWebsiteBtn: "ویرایش",
  deleteWebsiteBtn: "حذف",
  saveWebsiteBtn: "ذخیره",
  cancelWebsiteBtn: "انصراف",
  websiteNamePlaceholder: "نام وب‌سایت (مثال: یوتیوب)",
  websiteDomainPlaceholder: "دامنه آدرس (مثال: youtube.com)",

  // Ping Protocols
  pingSettingsTitle: "تنظیمات شبیه‌ساز پینگ",
  pingProtocolLabel: "پروتکل پینگ",
  incyPingLabel: "INCY Ping (درون‌شبکه‌ای)",
  tcpConnectLabel: "TCP Connect (پیشنهادی)",
  httpGetLabel: "HTTP GET (مرورگر کامل)",
  httpHeadLabel: "HTTP HEAD (هدر سبک)",
  icmpPingLabel: "ICMP Ping (پژواک شبکه)",
  pingTimeoutMs: "زمان انتظار پینگ (ms)",
  pingTargetUrl: "آدرس مقصد پینگ",
  pingCount: "تعداد دفعات تست",
  packetSize: "اندازه بسته (بایت)",
  profileLabel: "پروفایل پارامترها",

  // Filters & Management
  searchPlaceholder: "جستجو در نام کانفیگ، کشور یا آدرس سرور...",
  filterAllProtocols: "همه پروتکل‌ها",
  filterHealthyOnly: "فقط کانفیگ‌های متصل و سالم",
  deduplicateBtn: "حذف کانفیگ‌های تکراری",
  deduplicateMsg: "کانفیگ تکراری شناسایی و حذف شد!",
  clearAllBtn: "پاکسازی کل لیست",
  exportModalTitle: "صادرات و اشتراک‌گذاری کانفیگ‌ها",
  exportClashMeta: "خروجی Clash Meta / Mihomo (YAML)",
  exportSingbox: "خروجی Sing-box (JSON)",
  exportBase64: "لینک سابسکریپشن (Base64)",
  exportPlainText: "متن ساده (Plain URIs)",
  showQrCode: "نمایش QR Code",
  downloadFileBtn: "دانلود فایل",
  copyToClipboardBtn: "کپی در کلیپ‌بورد",
  closeBtn: "بستن",
  scoreBadgeLabel: "امتیاز هوشمند",
  noConfigsFound: "هیچ کانفیگی مطابق با فیلترهای انتخابی یافت نشد.",
  importConfigsFirst: "ابتدا تعدادی کانفیگ از کلیپ‌بورد، فایل یا لینک وارد کنید."
};

export const EnglishTranslation: Translation = {
  appName: "Xray Multi Test",
  currentCoreVersion: "Current Core Version: ",
  latestCoreVersion: "Latest Available Version: ",
  checkVersionBtn: "Check Core Update",
  downloadCoreBtn: "Download & Install Core",
  selectConfigTitle: "Import Configurations",
  importClipboard: "Import from Clipboard",
  importFile: "Import from Text File",
  importSubLink: "Import from Sub Link",
  subUrlPlaceholder: "Enter Subscription URL",
  runTestsBtn: "Start Diagnostics",
  testResultsTitle: "Diagnostics & Evaluation Report",
  tcpPingLabel: "TCP Ping",
  jitterLabel: "Jitter",
  packetLossLabel: "Packet Loss",
  realDelayLabel: "Real Delay (HTTP)",
  downloadSpeedLabel: "Download Speed",
  uploadSpeedLabel: "Upload Speed",
  websiteCheckLabel: "Website Reachability",
  statusChecking: "Testing...",
  statusSuccess: "Healthy & Online",
  statusFailed: "Connection Failed",
  exportHealthyBtn: "Export Healthy Configs",
  copySuccessMsg: "Healthy configs copied to clipboard successfully!",
  settingsTitle: "Custom Diagnostics Settings",
  localSocksPort: "Local SOCKS Port",
  testTimeout: "Test Timeout (ms)",
  customDomains: "Test Websites",
  languageBtn: "Switch Language (FA)",
  unknown: "Unknown",
  progressDownloading: "Downloading core binary...",
  progressExtracting: "Extracting and installing...",
  fragmentSettings: "Fragment Slicing (Anti-SNI Blocking)",
  enableFragment: "Enable Traffic Fragmentation",
  fragmentLength: "Fragment Length (bytes)",
  fragmentInterval: "Fragment Delay (ms)",
  muxSettings: "Multiplexing Config (Mux / XUDP)",
  enableMux: "Enable Traffic Multiplexing",
  muxConcurrency: "Max TCP Concurrency",
  xudpConcurrencyLabel: "XUDP Concurrency Limit",
  tlsFingerprint: "TLS uTLS Fingerprint Simulator",

  // Personas
  personaTitle: "Network Diagnostic Persona",
  personaGaming: "Gaming & Realtime",
  personaGamingDesc: "Low ping latency, minimal jitter and zero packet loss focus",
  personaStreaming: "Streaming & Video",
  personaStreamingDesc: "Maximum download bandwidth, buffer stability & YouTube test",
  personaAi: "AI & Web Browsing",
  personaAiDesc: "Guaranteed access to Gemini, ChatGPT, Claude, Instagram & Telegram",
  personaUpload: "Upload & File Transfer",
  personaUploadDesc: "Maximum uplink rate, heavy cloud session persistence",
  personaAllRounder: "All-Rounder Benchmark",
  personaAllRounderDesc: "Full comprehensive metrics benchmark to find the best proxy",

  // Presets & Filters
  testProfileLabel: "Test Settings Profile",
  profileUltra: "Ultra Fast (Gaming & Real-time)",
  profileBalanced: "Balanced (Default)",
  profileStable: "Deep & Stable (Heavy Load)",
  profileCustom: "Custom (Manual Parameters)",
  pingCountLabel: "Jitter Ping Count",
  speedVolumeLabel: "Speed Test Volume (MB)",
  speedProtocolLabel: "Speed Test Protocol",
  fragmentProfileLabel: "Traffic Fragment Profile",
  fragmentMci: "MCI Bypass (Standard)",
  fragmentMtn: "Irancell Aggressive (Microbytes)",
  fragmentTcp: "TCP Slicing (Ultra Stable)",
  fragmentCustom: "Custom (Manual Slices)",
  copyAllConfigs: "Copy All Healthy Configs",
  copyLimitedConfigs: "Copy Specified Count (Top Rank)",
  copyLimitCountLabel: "Number of Top Configs to Copy",
  addWebsiteBtn: "Add New Website",
  editWebsiteBtn: "Edit",
  deleteWebsiteBtn: "Delete",
  saveWebsiteBtn: "Save",
  cancelWebsiteBtn: "Cancel",
  websiteNamePlaceholder: "Website Name (e.g. YouTube)",
  websiteDomainPlaceholder: "Domain URL (e.g. youtube.com)",

  // Ping Protocols
  pingSettingsTitle: "Ping Simulator Settings",
  pingProtocolLabel: "Ping Protocol",
  incyPingLabel: "INCY Ping (In-Network)",
  tcpConnectLabel: "TCP Connect (Recommended)",
  httpGetLabel: "HTTP GET (Full Handshake)",
  httpHeadLabel: "HTTP HEAD (Light Header)",
  icmpPingLabel: "ICMP Ping (Network Echo)",
  pingTimeoutMs: "Ping Timeout (ms)",
  pingTargetUrl: "Target URL / IP",
  pingCount: "Test Count",
  packetSize: "Packet Size (bytes)",
  profileLabel: "Parameters Profile",

  // Filters & Management
  searchPlaceholder: "Search by remarks, country or server address...",
  filterAllProtocols: "All Protocols",
  filterHealthyOnly: "Healthy & Online Only",
  deduplicateBtn: "Remove Duplicates",
  deduplicateMsg: "duplicate configs removed!",
  clearAllBtn: "Clear All Configs",
  exportModalTitle: "Export & Share Configurations",
  exportClashMeta: "Clash Meta / Mihomo (YAML)",
  exportSingbox: "Sing-box Outbounds (JSON)",
  exportBase64: "Subscription Link (Base64)",
  exportPlainText: "Plain URIs (Text)",
  showQrCode: "Show QR Code",
  downloadFileBtn: "Download File",
  copyToClipboardBtn: "Copy to Clipboard",
  closeBtn: "Close",
  scoreBadgeLabel: "Smart Score",
  noConfigsFound: "No configurations match the selected filters.",
  importConfigsFirst: "Please import configurations first from clipboard, file or link."
};
