import { Translation } from './types';

export const PersianTranslation: Translation = {
  appName: "ایکس ری مالتی تست",
  currentCoreVersion: "نسخه فعلی هسته: ",
  latestCoreVersion: "آخرین نسخه منتشر شده: ",
  checkVersionBtn: "بررسی نسخه جدید هسته",
  downloadCoreBtn: "دانلود و بروزرسانی هسته",
  selectConfigTitle: "وارد کردن کانفیگ‌ها",
  importClipboard: "وارد کردن از کلیپ‌بورد",
  importFile: "وارد کردن از فایل متنی",
  importSubLink: "دریافت از لینک اشتراک",
  subUrlPlaceholder: "آدرس لینک اشتراک را وارد کنید",
  runTestsBtn: "شروع عیب‌یابی و تست",
  testResultsTitle: "نتایج ارزیابی کانفیگ‌ها",
  tcpPingLabel: "تأخیر TCP",
  jitterLabel: "جیتر (نوسان)",
  packetLossLabel: "پکت لاست",
  realDelayLabel: "تأخیر واقعی (HTTP)",
  downloadSpeedLabel: "سرعت دانلود",
  uploadSpeedLabel: "سرعت آپلود",
  websiteCheckLabel: "بررسی سایت‌های منتخب",
  statusChecking: "در حال ارزیابی...",
  statusSuccess: "متصل و سالم",
  statusFailed: "عدم اتصال",
  exportHealthyBtn: "خروجی و کپی سالم‌ها",
  copySuccessMsg: "کانفیگ‌ها با موفقیت در کلیپ‌بورد کپی شدند!",
  settingsTitle: "شخصی‌سازی تنظیمات تست",
  localSocksPort: "پورت محلی SOCKS",
  testTimeout: "زمان انتظار تست (ms)",
  customDomains: "سایت‌های تست دسترسی",
  languageBtn: "تغییر زبان (EN)",
  unknown: "نامشخص",
  progressDownloading: "در حال دریافت باینری هسته...",
  progressExtracting: "در حال نصب و استخراج هسته...",
  fragmentSettings: "پیکربندی فرگمنت (مبارزه با فیلترینگ SNI)",
  enableFragment: "فعالسازی فرگمنت ترافیکی",
  fragmentLength: "طول بازه بایت‌های فرگمنت",
  fragmentInterval: "میزان تأخیر بین فرگمنت‌ها (ms)",
  muxSettings: "پیکربندی چندگانه‌سازی (Mux / XUDP)",
  enableMux: "فعالسازی مالتی‌پلکسر ترافیک",
  muxConcurrency: "حداکثر کانکشن‌های همزمان TCP",
  xudpConcurrencyLabel: "همزمانی تونل‌های XUDP",
  tlsFingerprint: "شبیه‌ساز اثر انگشت uTLS",

  // Personas
  personaTitle: "پرسونا و هدف تست شبکه",
  personaGaming: "گیمینگ و آنلاین",
  personaGamingDesc: "سنجش پینگ بسیار پایین، کمترین جیتر و صفر درصد پکت‌لاست",
  personaStreaming: "استریم و دانلود",
  personaStreamingDesc: "حداکثر پهنای باند دانلود، تست ترافیکی یوتیوب و پایداری ویدیو",
  personaAi: "هوش مصنوعی و جمنای",
  personaAiDesc: "تست رفع تحریم Gemini، ChatGPT، Claude و شبکه‌های اجتماعی",
  personaUpload: "آپلود و تبادل دیتا",
  personaUploadDesc: "حداکثر نرخ بارگذاری، پایداری اتصالات طولانی ابری",
  personaAllRounder: "بنچمارک جامع",
  personaAllRounderDesc: "سنجش همه‌جانبه تمام فاکتورها جهت رتبه‌بندی دقیق بهترین کانفیگ‌ها",

  // Presets & Filters
  testProfileLabel: "پروفایل تنظیمات تست",
  profileUltra: "فوق‌العاده (Ultra Fast)",
  profileBalanced: "متعادل (پیش‌فرض استاندارد)",
  profileStable: "پایدار و عمیق (تحلیل پکت)",
  profileCustom: "کاستوم (تنظیم دستی متغیرها)",
  pingCountLabel: "تعداد دفعات ارسال پینگ جیتر",
  speedVolumeLabel: "حجم ترافیک دانلودی آزمایشی (MB)",
  speedProtocolLabel: "پروتکل تست سرعت",
  fragmentProfileLabel: "پروفایل‌های آماده فرگمنت",
  fragmentMci: "همراه اول (بای‌پس استاندارد)",
  fragmentMtn: "ایرانسل خشن (بایت‌های میکرو)",
  fragmentTcp: "تقطیع تی‌سی‌پی (فوق پایدار)",
  fragmentCustom: "سفارشی (طول و تاخیر دلخواه)",
  copyAllConfigs: "کپی تمام کانفیگ‌های سالم",
  copyLimitedConfigs: "کپی تعداد مشخص (برترین‌ها)",
  copyLimitCountLabel: "تعداد کانفیگ‌های برتر جهت کپی",
  addWebsiteBtn: "افزودن سایت هدف جدید",
  editWebsiteBtn: "ویرایش",
  deleteWebsiteBtn: "حذف",
  saveWebsiteBtn: "ذخیره تغییرات",
  cancelWebsiteBtn: "انصراف",
  websiteNamePlaceholder: "نام سایت (مثال: Gemini)",
  websiteDomainPlaceholder: "دامنه یا URL (مثال: gemini.google.com)",

  // Ping Protocols
  pingSettingsTitle: "پیکربندی شبیه‌ساز پینگ",
  pingProtocolLabel: "پروتکل ارسال پینگ",
  incyPingLabel: "INCY Ping (درون‌شبکه‌ای)",
  tcpConnectLabel: "TCP Connect (پیشنهادی)",
  httpGetLabel: "HTTP GET (هندشیک کامل)",
  httpHeadLabel: "HTTP HEAD (هدر سبک)",
  icmpPingLabel: "ICMP Ping (اکوی شبکه)",
  pingTimeoutMs: "زمان انتظار پاسخ پینگ (ms)",
  pingTargetUrl: "دامنه یا آدرس هدف",
  pingCount: "تعداد دفعات تست",
  packetSize: "حجم بسته (بایت)",
  profileLabel: "پروفایل پارامترها",

  // Filters & Management
  searchPlaceholder: "جستجو در ریمارک، کشور یا آدرس سرور...",
  filterAllProtocols: "تمامی پروتکل‌ها",
  filterHealthyOnly: "فقط کانفیگ‌های سالم و متصل",
  deduplicateBtn: "حذف کانفیگ‌های تکراری",
  deduplicateMsg: "کانفیگ تکراری پاکسازی شد!",
  clearAllBtn: "پاک کردن همه کانفیگ‌ها",
  exportModalTitle: "صادرات و اشتراک‌گذاری کانفیگ‌ها",
  exportClashMeta: "کلش متا / میهومو (YAML)",
  exportSingbox: "سینگ باکس (JSON)",
  exportBase64: "لینک سابسکرایب (Base64)",
  exportPlainText: "لینک‌های ساده (Plain Text)",
  showQrCode: "نمایش کد QR",
  downloadFileBtn: "دانلود فایل کانفیگ",
  copyToClipboardBtn: "کپی در کلیپ‌بورد",
  closeBtn: "بستن",
  scoreBadgeLabel: "امتیاز هوشمند",
  noConfigsFound: "هیچ کانفیگی مطابق فیلترهای انتخابی یافت نشد.",
  importConfigsFirst: "لطفاً ابتدا کانفیگ‌های خود را از کلیپ‌بورد، فایل یا لینک وارد کنید.",

  // In-App Update
  appUpdateTitle: "بروزرسانی نرم‌افزار",
  appUpdateAvailable: "نسخه جدید نرم‌افزار آماده دریافت است!",
  appUpdateLatest: "آخرین نسخه:",
  appUpdateCurrent: "نسخه فعلی:",
  appUpdateDownloadBtn: "دانلود و نصب مستقیم (APK)",
  appUpdateLaterBtn: "بعداً یادآوری کن",
  appUpdateCheckBtn: "بررسی آپدیت برنامه",
  appUpdateChecking: "در حال بررسی نسخه جدید...",
  appUpdateUpToDate: "شما از آخرین نسخه برنامه استفاده می‌کنید.",

  // Gemini Specific
  geminiStatusSafe: "جمنای: بدون تحریم و آماده",
  geminiStatusSanctioned: "جمنای: خطای تحریم (403/451)",
  geminiStatusPoisoned: "جمنای: اختلال DNS / مسدود"
};

export const EnglishTranslation: Translation = {
  appName: "Xray Multi Test",
  currentCoreVersion: "Current Core Version: ",
  latestCoreVersion: "Latest Release Version: ",
  checkVersionBtn: "Check for Core Update",
  downloadCoreBtn: "Download & Install Core",
  selectConfigTitle: "Import Configurations",
  importClipboard: "Import from Clipboard",
  importFile: "Import from Text File",
  importSubLink: "Import from Sub Link",
  subUrlPlaceholder: "Enter subscription link URL",
  runTestsBtn: "Start Benchmark Diagnostics",
  testResultsTitle: "Diagnostics & Evaluation Results",
  tcpPingLabel: "TCP Ping",
  jitterLabel: "Jitter Variance",
  packetLossLabel: "Packet Loss",
  realDelayLabel: "HTTP Real Delay",
  downloadSpeedLabel: "Download Speed",
  uploadSpeedLabel: "Upload Speed",
  websiteCheckLabel: "Target Websites Check",
  statusChecking: "Testing network...",
  statusSuccess: "Connected / Online",
  statusFailed: "Failed / Timeout",
  exportHealthyBtn: "Export & Copy Healthy",
  copySuccessMsg: "Configurations copied to clipboard successfully!",
  settingsTitle: "Diagnostics Settings & Tuning",
  localSocksPort: "Local SOCKS Port",
  testTimeout: "Ping Timeout (ms)",
  customDomains: "Reachability Test Websites",
  languageBtn: "Language (FA)",
  unknown: "Unknown",
  progressDownloading: "Downloading core binary...",
  progressExtracting: "Extracting and installing core...",
  fragmentSettings: "Fragment Tuning (SNI Bypass)",
  enableFragment: "Enable Traffic Fragmentation",
  fragmentLength: "Fragment Length Range (Bytes)",
  fragmentInterval: "Delay Interval (ms)",
  muxSettings: "Multiplexing (Mux / XUDP)",
  enableMux: "Enable Multiplexing",
  muxConcurrency: "Max TCP Streams",
  xudpConcurrencyLabel: "XUDP UDP Streams",
  tlsFingerprint: "uTLS Fingerprint Emulator",

  // Personas
  personaTitle: "Testing Persona & Objective",
  personaGaming: "Gaming & Low Latency",
  personaGamingDesc: "Prioritizes ultra-low ping, minimal jitter, and zero packet loss",
  personaStreaming: "Streaming & Bandwidth",
  personaStreamingDesc: "Evaluates high download throughput and YouTube streaming smoothness",
  personaAi: "AI & Gemini Bypass",
  personaAiDesc: "Verifies clean, unsanctioned access to Gemini, ChatGPT, Claude, and socials",
  personaUpload: "Upload & Cloud Transfer",
  personaUploadDesc: "Measures high uplink bandwidth and long-session TCP stability",
  personaAllRounder: "Comprehensive Benchmark",
  personaAllRounderDesc: "Full multi-factor rating for finding top-performing configs",

  // Presets & Filters
  testProfileLabel: "Diagnostic Preset Profile",
  profileUltra: "Ultra Fast (Quick Pings)",
  profileBalanced: "Balanced (Standard Default)",
  profileStable: "Stable (Deep Packet Analysis)",
  profileCustom: "Custom (Manual Parameters)",
  pingCountLabel: "Jitter Ping Count",
  speedVolumeLabel: "Speed Test Volume (MB)",
  speedProtocolLabel: "Speed Test Protocol",
  fragmentProfileLabel: "Traffic Fragment Profile",
  fragmentMci: "MCI Bypass (Standard)",
  fragmentMtn: "Irancell Aggressive (Microbytes)",
  fragmentTcp: "TCP Slicing (Ultra Stable)",
  fragmentCustom: "Custom (Manual Slices)",
  copyAllConfigs: "Copy All Healthy Configs",
  copyLimitedConfigs: "Copy Specified Count (Top Rank)",
  copyLimitCountLabel: "Number of Top Configs to Copy",
  addWebsiteBtn: "Add New Website",
  editWebsiteBtn: "Edit",
  deleteWebsiteBtn: "Delete",
  saveWebsiteBtn: "Save",
  cancelWebsiteBtn: "Cancel",
  websiteNamePlaceholder: "Website Name (e.g. Gemini)",
  websiteDomainPlaceholder: "Domain URL (e.g. gemini.google.com)",

  // Ping Protocols
  pingSettingsTitle: "Ping Simulator Settings",
  pingProtocolLabel: "Ping Protocol",
  incyPingLabel: "INCY Ping (In-Network)",
  tcpConnectLabel: "TCP Connect (Recommended)",
  httpGetLabel: "HTTP GET (Full Handshake)",
  httpHeadLabel: "HTTP HEAD (Light Header)",
  icmpPingLabel: "ICMP Ping (Network Echo)",
  pingTimeoutMs: "Ping Timeout (ms)",
  pingTargetUrl: "Target URL / IP",
  pingCount: "Test Count",
  packetSize: "Packet Size (bytes)",
  profileLabel: "Parameters Profile",

  // Filters & Management
  searchPlaceholder: "Search by remarks, country or server address...",
  filterAllProtocols: "All Protocols",
  filterHealthyOnly: "Healthy & Online Only",
  deduplicateBtn: "Remove Duplicates",
  deduplicateMsg: "duplicate configs removed!",
  clearAllBtn: "Clear All Configs",
  exportModalTitle: "Export & Share Configurations",
  exportClashMeta: "Clash Meta / Mihomo (YAML)",
  exportSingbox: "Sing-box Outbounds (JSON)",
  exportBase64: "Subscription Link (Base64)",
  exportPlainText: "Plain URIs (Text)",
  showQrCode: "Show QR Code",
  downloadFileBtn: "Download File",
  copyToClipboardBtn: "Copy to Clipboard",
  closeBtn: "Close",
  scoreBadgeLabel: "Smart Score",
  noConfigsFound: "No configurations match the selected filters.",
  importConfigsFirst: "Please import configurations first from clipboard, file or link.",

  // In-App Update
  appUpdateTitle: "Application Update",
  appUpdateAvailable: "A new version of the app is available!",
  appUpdateLatest: "Latest Version:",
  appUpdateCurrent: "Current Version:",
  appUpdateDownloadBtn: "Download & Install APK",
  appUpdateLaterBtn: "Remind Me Later",
  appUpdateCheckBtn: "Check for App Update",
  appUpdateChecking: "Checking for updates...",
  appUpdateUpToDate: "You have the latest version.",

  // Gemini Specific
  geminiStatusSafe: "Gemini: Clean & Unsanctioned",
  geminiStatusSanctioned: "Gemini: Region Sanction Block (403/451)",
  geminiStatusPoisoned: "Gemini: DNS Poisoned / Blocked"
};
